# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew build
      - name: Verify IDEA compatibility
        uses: thepieterdc/intellij-plugin-verifier-action@v1.1.2
        with:
          plugin: '/home/runner/work/ansible-vault-editor-idea-plugin/ansible-vault-editor-idea-plugin/build/distributions/*'
          versions: |
            193.1
            201.1
            LATEST-EAP-SNAPSHOT
