# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Verify IDEA compatibility
        uses: thepieterdc/intellij-plugin-verifier-action@v1.1.2
        with:
          plugin: '/home/runner/work/ansible-vault-editor-idea-plugin/ansible-vault-editor-idea-plugin/build/distributions/*'
          versions: |
            2019.3.3
            LATEST-EAP-SNAPSHOT
      - name: Notify to Telegram
        uses: yanzay/notify-telegram@v0.1.0
        with:
          chat: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          status: ${{ job.status }}
